---

- name: apt - update package information
  ansible.builtin.apt:
    update_cache: yes
  become: true
  ignore_errors: true

- name: apt - upgrade all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: apt - remove useless packages from the cache
  tags:
    - cleanup
  ansible.builtin.apt:
    autoclean: yes
  become: true

- name: apt - remove dependencies that are no longer required
  tags:
    - cleanup
  ansible.builtin.apt:
    autoremove: yes
  become: true
