---

- name: APT - update package information
  ansible.builtin.apt:
    update_cache: true
  become: true
  ignore_errors: true

- name: APT - update all packages to the latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

- name: APT - remove useless packages from the cache
  tags:
    - cleanup
  ansible.builtin.apt:
    autoclean: true
  become: true

- name: APT - remove dependencies that are no longer required
  tags:
    - cleanup
  ansible.builtin.apt:
    autoremove: true
  become: true
