---

- name: composer - debug composer executable path
  tags:
    - composer
  debug:
    msg:
      - 'composer executable path: {{ mega_update_composer.stdout }}'
    verbosity: 1

- name: composer - update composer itself to the latest version
  composer:
    command: self-update
    global_command: yes

- name: composer - determine composer global home path
  ignore_errors: true
  command:
    argv:
      - '{{ mega_update_composer.stdout }}'
      - config
      - --global
      - --absolute
      - home
  register: mega_update_composer_global_home
  when: mega_update_composer is succeeded

- name: composer - check composer global dependencies file exists
  ignore_errors: true
  stat:
    path: '{{ mega_update_composer_global_home}}/composer.json'
  register: mega_update_composer_global_dependencies
  when: mega_update_composer_global_home is defined

- name: composer - upgrade global composer packages
  composer:
    command: update
    global_command: yes
  when: mega_update_composer_global_dependencies.stat.exists
