---

- name: homebrew - fetch the newest version of homebrew and all formulae
  community.general.homebrew:
    update_homebrew: yes

- name: homebrew - upgrade outdated and unpinned brews
  community.general.homebrew:
    upgrade_all: yes

- name: homebrew cask - upgrade all outdated casks
  community.general.homebrew_cask:
    upgrade_all: yes

- name: homebrew - remove outdated downloads
  tags:
    - cleanup
  ansible.builtin.command:
    argv:
      - '{{ mega_update_homebrew.stdout }}'
      - cleanup
