---

- name: homebrew - fetch the newest version of homebrew and all formulae
  tags:
    - homebrew
  homebrew:
    update_homebrew: yes

- name: homebrew - upgrade outdated and unpinned brews
  tags:
    - homebrew
  homebrew:
    upgrade_all: yes

- name: homebrew cask - upgrade all outdated casks
  tags:
    - homebrew
  homebrew_cask:
    upgrade_all: yes

- name: homebrew - remove outdated downloads
  tags:
    - homebrew
    - cleanup
  command: brew cleanup
