---

- name: Homebrew - fetch the newest version of homebrew and all formulae
  community.general.homebrew:
    update_homebrew: true

- name: Homebrew - upgrade outdated and unpinned brews
  community.general.homebrew:
    upgrade_all: true

- name: Homebrew cask - upgrade all outdated casks
  community.general.homebrew_cask:
    upgrade_all: true
  when: 'ansible_os_family == "Darwin"' # Homebrew casks are only supported on macOS

- name: Homebrew - remove outdated downloads
  tags:
    - cleanup
  ansible.builtin.command:
    argv:
      - '{{ mega_update_homebrew.stdout }}'
      - cleanup
  register: mega_update_homebrew_cleanup
  changed_when: mega_update_homebrew_cleanup.rc != 0
