---

- name: Homebrew - fetch the newest version of homebrew and all formulae
  community.general.homebrew:
    update_homebrew: true

- name: Homebrew - upgrade outdated and unpinned brews
  community.general.homebrew:
    upgrade_all: true

- name: Homebrew cask - upgrade all outdated casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Homebrew - remove outdated downloads
  tags:
    - cleanup
  ansible.builtin.command:
    argv:
      - '{{ mega_update_homebrew.stdout }}'
      - cleanup
