---

# APT
- name: Import APT Tasks
  tags:
    - apt
  import_tasks: apt.yml
  when: 'ansible_os_family == "Debian"'

# Composer
- name: Composer - determine composer executable path
  ignore_errors: true
  tags:
    - composer
  ansible.builtin.command:
    argv:
      - which
      - composer
  register: mega_update_composer
  changed_when: mega_update_composer.rc != 0

- name: Import Composer Tasks
  tags:
    - composer
  import_tasks: composer.yml
  when: mega_update_composer is succeeded

# Docker
- name: Docker - gather facts on docker host
  tags:
    - docker
  community.docker.docker_host_info:
  register: mega_update_docker_host

- name: Import Docker Tasks
  tags:
    - docker
  import_tasks: docker.yml
  when: 'not mega_update_docker_host.failed'

# HomeBrew
- name: Homebrew - determine homebrew executable path
  ignore_errors: true
  tags:
    - homebrew
  ansible.builtin.command:
    argv:
      - which
      - brew
  register: mega_update_homebrew
  changed_when: mega_update_homebrew.rc != 0

- name: Import HomeBrew Tasks
  tags:
    - homebrew
  import_tasks: homebrew.yml
  when: mega_update_homebrew is succeeded

# NPM
- name: NPM - determine npm executable path
  ignore_errors: true
  tags:
    - npm
  ansible.builtin.command:
    argv:
      - which
      - npm
  register: mega_update_npm
  changed_when: mega_update_npm.rc != 0

- name: Import NPM Tasks
  tags:
    - npm
  import_tasks: npm.yml
  when: mega_update_npm is succeeded

# OSX
- name: Import OSX Tasks
  tags:
    - osx
  import_tasks: osx.yml
  when: 'ansible_os_family == "Darwin"'
