---

- name: Phive - update phive itself to the latest version
  ansible.builtin.command:
    argv:
      - '{{ mega_update_phive.stdout }}'
      - self-update
  register: mega_update_phive_selfupdate
  changed_when: '"You already have the newest" not in mega_update_phive_selfupdate.stdout'

- name: Phive - update configured phars
  ansible.builtin.command:
    chdir: $HOME
    argv:
      - '{{ mega_update_phive.stdout }}'
      - update
  register: mega_update_phive_update
  changed_when: mega_update_phive_update.rc != 0
